version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      PGUSER: watchuser
      PGPASSWORD: watchpass
      PGDATABASE: watchdb
      PGHOST: db
    depends_on:
      - db
    volumes:
      - ./backend/images:/app/images  # 👈 Mount the images directory

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: watchuser
      POSTGRES_PASSWORD: watchpass
      POSTGRES_DB: watchdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
